name: 'SWM GitHub Actions Basic'

on: push

env:
  GLOBAL_LEVEL: "This value comes from the JOB level"
  PRESET_VALUE: "This value is preset value"

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    env:
      JOB_LEVEL_1: "This value comes from the JOB level 1"

    steps:
    # -는 객체, 배열
    - name: Say Hello World 1
      shell: bash
      env:
        STEP_LEVEL_1: "This value comes from the JOB step level 1"
      run: |
        echo "Hello World from step 1"
        echo "Global Level: ${{ env.GLOBAL_LEVEL }}"
        echo "Job Level 1: ${{ env.JOB_LEVEL_1 }}"
        echo "Job Level 2: ${{ env.JOB_LEVEL_2 }}"
        echo "Step Level 1: ${{ env.STEP_LEVEL_1 }}"
        echo "Step Level 2: ${{ env.STEP_LEVEL_2 }}"

    - name: Say Hello World 2
      shell: pwsh
      env:
        STEP_LEVEL_2: "This value comes from the JOB step level2"
      run: |
        echo "Hello World from step 2"
        echo "Global Level: ${{ env.GLOBAL_LEVEL }}"
        echo "Job Level 1: ${{ env.JOB_LEVEL_1 }}"
        echo "Job Level 2: ${{ env.JOB_LEVEL_2 }}"
        echo "Step Level 1: ${{ env.STEP_LEVEL_1 }}"
        echo "Step Level 2: ${{ env.STEP_LEVEL_2 }}"

    - name: Set envirment variable 1
      shell: bash
      run: |
        echo "STEP_LEVEL_1=This is the value 1 set in the step" >> $GITHUB_ENV

    - name: Set envirment variable 1
      shell: pwsh
      run: |
        echo "STEP_LEVEL_2=This is the value 2 set in the step" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Get environment variables in PowerShell
      shell: pwsh
      run: |
        echo "Value 1: $env:STEP_LEVEL_1"
        echo "Value 2: $env:STEP_LEVEL_2"
    
    - name: Get environment variables in Bash
      shell: bash
      run: |
        echo "Value 1: $STEP_LEVEL_1"
        echo "Value 2: $STEP_LEVEL_2"

    - name: Set output value
      id: swm
      shell: bash
      run: |
        first_value="This is the value for the first output
        echo "::set-output name=april05::$first_value"

    - name: Get output value
      shell: bash
      run: |
        echo "The value of the first output is: ${{ steps.swm.outputs.april05 }}"

  second-job:
    name: 'Second Job'

    runs-on: ubuntu-latest

    env:
      JOB_LEVEL_2: "This value comes from the JOB level 2"

    steps:
    # -는 객체, 배열
    - name: Say Hello World 1
      shell: bash
      env:
        STEP_LEVEL_1: "This value comes from the JOB step level 1"
      run: |
        echo "Hello World from step 1"

    - name: Say Hello World 2
      shell: pwsh
      env:
        STEP_LEVEL_2: "This value comes from the JOB step level2"
      run: |
        echo "Hello World from step 2"